version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - test
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    networks:
      - test
networks:
  test: {}

